SELECT B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(A.SALES * B.PRICE) TOTAL_SALES
  FROM BOOK_SALES A,
       BOOK B,
       AUTHOR C
 WHERE 1=1
   AND A.BOOK_ID = B.BOOK_ID
   AND B.AUTHOR_ID = C.AUTHOR_ID
   AND DATE_FORMAT(A.SALES_DATE, '%Y%m') = '202201'
 GROUP BY B.AUTHOR_ID, B.CATEGORY
 ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;