SELECT C.AUTHOR_ID,
       C.AUTHOR_NAME,
       B.CATEGORY,
       SUM(A.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES A,
     BOOK B,
     AUTHOR C
WHERE A.BOOK_ID = B.BOOK_ID
  AND B.AUTHOR_ID = C.AUTHOR_ID
  AND TO_CHAR(A.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY
ORDER BY C.AUTHOR_ID ASC, B.CATEGORY DESC;