SELECT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE A,
     ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
AND A.PRODUCT_ID = B.PRODUCT_ID
AND A.ONLINE_SALE_ID <> B.ONLINE_SALE_ID
GROUP BY A.USER_ID, A.PRODUCT_ID
ORDER BY USER_ID ASC, PRODUCT_ID DESC;
