SELECT K.PRODUCT_CODE, SUM(K.SALES) AS SALES
FROM
(
    SELECT A.PRODUCT_CODE, B.SALES_AMOUNT * A.PRICE AS SALES
    FROM PRODUCT A, OFFLINE_SALE B
    WHERE 1 = 1
    AND A.PRODUCT_ID = B.PRODUCT_ID
) K
GROUP BY K.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;