-- 코드를 입력하세요
SELECT K.ANIMAL_ID, K.NAME
FROM
(
    SELECT A.ANIMAL_ID, A.NAME, RANK() OVER (ORDER BY B.DATETIME - A.DATETIME DESC) AS RANK
    FROM ANIMAL_INS A, ANIMAL_OUTS B
    WHERE A.ANIMAL_ID = B.ANIMAL_ID (+)
    AND B.ANIMAL_ID IS NOT NULL
) k
WHERE 1=1
AND K.RANK < 3;