SELECT A.FOOD_TYPE,	A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A,
(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
      FROM REST_INFO
    GROUP BY FOOD_TYPE
) K
WHERE A.FOOD_TYPE = K.FOOD_TYPE
  AND A.FAVORITES = K.FAVORITES
ORDER BY A.FOOD_TYPE DESC;