SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
  FROM REST_INFO A,
        (
            SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
              FROM REST_INFO
             WHERE 1=1
             GROUP BY FOOD_TYPE
        ) B
 WHERE 1=1
   AND A.FOOD_TYPE = B.FOOD_TYPE
   AND A.FAVORITES = B.FAVORITES
 ORDER BY FOOD_TYPE DESC