SELECT DISTINCT A.CAR_ID,
       CASE
            WHEN B.CAR_ID IS NULL THEN '대여 가능'
            ELSE '대여중'
       END AS AVAILABILITY
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
       LEFT OUTER JOIN (
            SELECT DISTINCT CAR_ID 
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
             WHERE DATE_FORMAT(START_DATE, '%Y%m%d') <= '20221016'
               AND DATE_FORMAT(END_DATE, '%Y%m%d') >= '20221016'
        ) B ON A.CAR_ID = B.CAR_ID
  ORDER BY CAR_ID DESC;
  