SELECT K.NAME, K.DATETIME
FROM 
(
    SELECT RANK() OVER (ORDER BY A.DATETIME ASC) AS RANK,
           A.NAME,
           A.DATETIME
    FROM ANIMAL_INS A,
         ANIMAL_OUTS B
    WHERE 1 = 1
      AND A.ANIMAL_ID = B.ANIMAL_ID (+)
      AND B.ANIMAL_ID IS NULL
    ORDER BY A.DATETIME ASC
) K
WHERE K.RANK < 4
ORDER BY K.RANK ASC;