SELECT A.FLAVOR
FROM
(
    SELECT FLAVOR, RANK() OVER (ORDER BY SUM(TOTAL_ORDER) DESC) AS RANK
    FROM
        (
            SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM FIRST_HALF
            GROUP BY FLAVOR

            UNION ALL

            SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR
        ) K
    GROUP BY FLAVOR
) A
WHERE A.RANK <= 3;