WITH STD AS (
SELECT 0 AS HOUR FROM DUAL UNION ALL
SELECT 1 AS HOUR FROM DUAL UNION ALL
SELECT 2 AS HOUR FROM DUAL UNION ALL
SELECT 3 AS HOUR FROM DUAL UNION ALL
SELECT 4 AS HOUR FROM DUAL UNION ALL
SELECT 5 AS HOUR FROM DUAL UNION ALL
SELECT 6 AS HOUR FROM DUAL UNION ALL
SELECT 7 AS HOUR FROM DUAL UNION ALL
SELECT 8 AS HOUR FROM DUAL UNION ALL
SELECT 9 AS HOUR FROM DUAL UNION ALL
SELECT 10 AS HOUR FROM DUAL UNION ALL
SELECT 11 AS HOUR FROM DUAL UNION ALL
SELECT 12 AS HOUR FROM DUAL UNION ALL
SELECT 13 AS HOUR FROM DUAL UNION ALL
SELECT 14 AS HOUR FROM DUAL UNION ALL
SELECT 15 AS HOUR FROM DUAL UNION ALL
SELECT 16 AS HOUR FROM DUAL UNION ALL
SELECT 17 AS HOUR FROM DUAL UNION ALL
SELECT 18 AS HOUR FROM DUAL UNION ALL
SELECT 19 AS HOUR FROM DUAL UNION ALL
SELECT 20 AS HOUR FROM DUAL UNION ALL
SELECT 21 AS HOUR FROM DUAL UNION ALL
SELECT 22 AS HOUR FROM DUAL UNION ALL
SELECT 23 AS HOUR FROM DUAL
),
DATA AS (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR, ANIMAL_ID
    FROM ANIMAL_OUTS
)
SELECT S.HOUR, NVL(COUNT(D.ANIMAL_ID), 0) AS COUNT
  FROM STD S,
       DATA D
WHERE S.HOUR = D.HOUR (+)
GROUP BY S.HOUR
ORDER BY S.HOUR ASC;