SELECT HISTORY_ID,
       CAR_ID,
       TO_CHAR(START_DATE, 'YYYY-MM-DD') AS START_DATE,
       TO_CHAR(END_DATE, 'YYYY-MM-DD') AS END_DATE,
       --END_DATE - START_DATE AS DIF,
       --대여일, 반납일 자체를 포함하기 위해서 날짜 차이 + 1 계산함
       CASE WHEN (END_DATE - START_DATE) + 1 < 30 THEN '단기 대여'
       ELSE '장기 대여' END AS RENT_TYPE
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE TO_CHAR(START_DATE, 'YYYYMM') = '202209'
 ORDER BY HISTORY_ID DESC