SELECT A.USER_ID, A.NICKNAME, K.SUM AS TOTAL_SALES
FROM
USED_GOODS_USER A,
(
    SELECT WRITER_ID, SUM(PRICE) AS SUM
      FROM USED_GOODS_BOARD
     WHERE STATUS = "DONE"
     GROUP BY WRITER_ID
     HAVING SUM(PRICE) >= 700000
) K
WHERE K.WRITER_ID = A.USER_ID
ORDER BY K.SUM ASC;