SELECT B.MEMBER_NAME, A.REVIEW_TEXT, TO_CHAR(A.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW A,
MEMBER_PROFILE B,
(
    SELECT MEMBER_ID, RANK() OVER (ORDER BY COUNT(*) DESC) as RANK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
) K
WHERE K.RANK = 1
AND K.MEMBER_ID = A.MEMBER_ID 
AND A.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;