SELECT CAST(DATE_FORMAT(A.START_DATE, '%c') AS UNSIGNED) MONTH,
       A.CAR_ID,
       COUNT(*) RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A,
        (
        SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
         WHERE 1=1
           AND DATE_FORMAT(START_DATE, '%Y%m') BETWEEN '202208' AND '202210'
         GROUP BY CAR_ID
         HAVING COUNT(*) >= 5
        ) CAR
 WHERE A.CAR_ID = CAR.CAR_ID
   AND DATE_FORMAT(START_DATE, '%Y%m') BETWEEN '202208' AND '202210'
 GROUP BY CAST(DATE_FORMAT(A.START_DATE, '%c') AS UNSIGNED), A.CAR_ID
 ORDER BY MONTH ASC, CAR_ID DESC;