SELECT TO_NUMBER(TO_CHAR(A.START_DATE, 'MM')) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A,
(
   SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
    GROUP BY CAR_ID
    HAVING COUNT(*) > 4
) K
WHERE K.CAR_ID = A.CAR_ID
AND TO_CHAR(A.START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
GROUP BY TO_NUMBER(TO_CHAR(A.START_DATE, 'MM')), A.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;
