/*
WITH SC AS (
 SELECT NAME,
        LOCATE('1', CONVERT(LPAD(BIN(CODE), 15, 0), CHAR)) AS IDX
   FROM SKILLCODES
  WHERE NAME IN ('Python', 'C#')
)
SELECT A.ID,
       A.EMAIL,
       A.FIRST_NAME,
       A.LAST_NAME
 FROM DEVELOPERS A
WHERE SUBSTR(CONVERT(LPAD(BIN(A.SKILL_CODE), 15, 0), CHAR), (SELECT IDX FROM SC WHERE NAME = 'Python'), 1) = 1
   OR SUBSTR(CONVERT(LPAD(BIN(A.SKILL_CODE), 15, 0), CHAR), (SELECT IDX FROM SC WHERE NAME = 'C#'), 1) = 1
ORDER BY A.ID ASC;
*/

SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
  FROM DEVELOPERS A,
       SKILLCODES B
 WHERE B.NAME IN ('Python', 'C#')
   AND A.SKILL_CODE & B.CODE > 0
 ORDER BY A.ID ASC;
 