-- 코드를 작성해주세요
SELECT K.SCORE, K.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM
(
    SELECT EMP_NO, YEAR, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
    ORDER BY SCORE DESC
    LIMIT 1
) K,
HR_EMPLOYEES A
WHERE K.EMP_NO = A.EMP_NO;
