SELECT A.CATEGORY, SUM(SALES) AS TOTAL_SALES
  FROM BOOK A
       LEFT OUTER JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
 WHERE 1=1
   AND DATE_FORMAT(B.SALES_DATE, '%Y%m') = '202201'
 GROUP BY A.CATEGORY
 ORDER BY 1;