SELECT A.CATEGORY,A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A,
(
    SELECT CATEGORY, MAX(PRICE) AS PRICE
      FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) K
WHERE A.CATEGORY = K.CATEGORY
  AND A.PRICE = K.PRICE
  AND A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;