SELECT *
FROM
(
SELECT CASE
            WHEN 1=1
             AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0
             AND SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES GROUP BY CATEGORY HAVING CATEGORY = 'Front End') > 0 THEN 'A'
            WHEN 1=1
             AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
            WHEN 1=1
             AND SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES GROUP BY CATEGORY HAVING CATEGORY = 'Front End') > 0 THEN 'C'
            ELSE NULL
       END AS GRADE, ID, EMAIL
  FROM DEVELOPERS A
) K
WHERE K.GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;
 
